import pygame
WIDTH, HEIGHT = 480, 720
PLAYER_WIDTH, PLAYER_HEIGHT = 60, 80
PLAYER_SPEED = 300
LANES = 3
LANE_WIDTH = 120
GROUND_Y = HEIGHT - 2*PLAYER_HEIGHT
OBSTACLE_Y = -GROUND_Y
MIN_SPAWN_INTERVAL, MAX_SPAWN_INTERVAL = 0.8, 2.5
PLAYING, GAME_OVER = 0, 1
DIFFICULTY_SCALING = 0.1
MAX_OBSTACLE_SPEED = 1000
BASE_LANE_SWITCH_TIME = 0.25
BASE_OBSTACLE_SPEED = 350
NO_CLIP = True

def make_fonts():
    pygame.font.init()
    FONT, SMALL_FONT = pygame.font.Font(None, 74), pygame.font.Font(None, 37)
    return FONT, SMALL_FONT
